### ISSUE TITLE
Use of Date.now() in reducer is not pure

### ISSUE THREAD

**Issue by markerikson** [lokhmakov/redux-journal#1]
Redux reducers _should_ be pure and deterministic.  Calling `Date.now()` in a reducer will produce different results even with the same inputs to the reducer.  The current code will technically work, but it will not behave as expected during things like time-travel debugging.

**Comment by lokhmakov** [comment]
Your suggestions? Move it to actions?

**Comment by markerikson** [comment]
Yeah, generally you'd want to put stuff like generating unique IDs or getting a current timestamp into an action creator.

**Comment by lokhmakov** [comment]
done https://github.com/lokhmakov/redux-journal/commit/d7472d912751b62d8a8807ec46ee37ac582a85aa
